kitchen/urls.py
from django.urls import path

from .views import (index,
                    DishTypeListView,
                    DishListView,
                    DishDetailView,
                    DishCreateView,
                    DishUpdateView,
                    DishDeleteView,
                    DishTypeCreateView,
                    DishTypeUpdateView,
                    DishTypeDeleteView,
                    CookListView,
                    CookDetailView,
                    CookCreateView,
                    CookDeleteView,
                    CookUpdateView)

urlpatterns = [
    path("", index, name="index"),
    path("dish-types/", DishTypeListView.as_view(), name="dish-types-list"),
    path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-types-create"),
    path("dish-types/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-types-update"),
    path("dish-types/<int:pk>/delete/", DishTypeDeleteView.as_view(), name="dish-types-delete"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
]

app_name = "kitchen"

kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", include("kitchen.urls", namespace="kitchen")),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path("__debug__/", include("debug_toolbar.urls")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/search.html
{% load crispy_forms_filters %}

<form action="" method="get" class="form-inline">
  {{ search_form|crispy }}
  <input type="submit" value="🔎" class="btn btn-secondary">
</form>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: {{ user.username }}</li>
    <li class="list-group-item">
      <form action="{% url 'logout' %}" method="POST" >
        {% csrf_token %}
        <button type="submit" class="btn btn-link p-0 m-0">Logout</button>
      </form>
    </li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
  {% endif %}
  <li class="list-group-item"><a href="{% url 'kitchen:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'kitchen:dish-types-list' %}">All Dish Type</a></li>
  <li class="list-group-item"><a href="{% url 'kitchen:dish-list' %}">All Dishes</a></li>
  <li class="list-group-item"><a href="{% url 'kitchen:cook-list' %}">All Cooks</a></li>
</ul>