kitchen/urls.py
from django.urls import path

from .views import (index,
                    DishTypeListView,
                    DishListView,
                    DishDetailView,
                    DishCreateView,
                    DishUpdateView,
                    DishDeleteView,
                    DishTypeCreateView,
                    DishTypeUpdateView,
                    DishTypeDeleteView,
                    CookListView,
                    CookDetailView,
                    CookCreateView,
                    CookDeleteView,
                    CookUpdateView)

urlpatterns = [
    path("", index, name="index"),
    path("dish-types/", DishTypeListView.as_view(), name="dish-types-list"),
    path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-types-create"),
    path("dish-types/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-types-update"),
    path("dish-types/<int:pk>/delete/", DishTypeDeleteView.as_view(), name="dish-types-delete"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
]

app_name = "kitchen"

kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", include("kitchen.urls", namespace="kitchen")),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path("__debug__/", include("debug_toolbar.urls")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering =["name"]

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    year_of_experience = models.IntegerField(
        null=True,
        blank=True,
        validators=[MinValueValidator(1)]
    )

    def __str__(self):
        return f"{self.username} {self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("kitchen:cook-detail", kwargs={"pk": self.pk})


class Dish(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE, related_name="dishes")
    cooks = models.ManyToManyField(Cook, related_name="dishes")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} {self.dish_type} {self.price}"

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from kitchen.models import Cook, Dish


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    class Meta:
        model = Dish
        fields = "__all__"


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "year_of_experience",
            "first_name",
            "last_name",
        )


class CookUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = [
            "first_name",
            "last_name",
            "username",
            "year_of_experience"
        ]


class SearchForm(forms.Form):
    param = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search"})
    )

kitchen/views.py
from django.contrib.admin.templatetags.admin_list import search_form
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import CookCreationForm, DishForm, SearchForm, CookUpdateForm
from kitchen.models import (DishType,
                            Dish,
                            Cook)


@login_required
def index(request):
    """View function for the home page of the site."""
    num_dish_type = DishType.objects.count()
    num_dish = Dish.objects.count()
    num_cooks = Cook.objects.count()

    context = {
        "num_dish_type": num_dish_type,
        "num_dish": num_dish,
        "num_cooks": num_cooks,
    }

    return render(request, "kitchen/index.html", context=context)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    template_name = "kitchen/dish_type_list.html"
    context_object_name = "dish_type_list"
    paginate_by = 4

    def get_context_data(
        self, *, object_list = ..., **kwargs
    ):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        param = self.request.GET.get("param", "")
        context["search_form"] = SearchForm(
            initial={"param": param}
        )
        return context

    def get_queryset(self):
        form = SearchForm(self.request.GET)
        queryset = DishType.objects.all()

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["param"]
            )
        return queryset

class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-types-list")
    template_name = "kitchen/dish_type_form.html"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-types-list")
    template_name = "kitchen/dish_type_form.html"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-types-list")
    template_name = "kitchen/dish_type_confirm_delete.html"


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    queryset = Dish.objects.select_related("dish_type")
    paginate_by = 4

    def get_context_data(
        self, *, object_list = ..., **kwargs
    ):
        context = super(DishListView, self).get_context_data(**kwargs)
        param = self.request.GET.get("param", "")
        context["search_form"] = SearchForm(
            initial={"param": param}
        )
        return context

    def get_queryset(self):
        form = SearchForm(self.request.GET)
        queryset = Dish.objects.select_related("dish_type")

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["param"]
            )
        return queryset

class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5

    def get_context_data(
        self, *, object_list = ..., **kwargs
    ):
        context = super(CookListView, self).get_context_data(**kwargs)
        param = self.request.GET.get("param", "")
        context["search_form"] = SearchForm(
            initial={"param": param}
        )
        return context

    def get_queryset(self):
        form = SearchForm(self.request.GET)
        queryset = Cook.objects.order_by("id")

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["param"],
            )
        return queryset

class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen:cook-list")


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookUpdateForm
    success_url = reverse_lazy("kitchen:cook-detail")




templates/kitchen/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
	<h1>Delete {{ cook.first_name }} {{ cook.last_name }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>
{% endblock %}

templates/kitchen/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Cook
    <a href="{% url 'kitchen:cook-delete' pk=cook.id %}" class="btn btn-danger">
      Delete
    </a>
    <a href="{% url 'kitchen:cook-update' pk=cook.id %}" class="btn btn-secondary">
      Update
    </a>
  </h1>
  <p>First name : {{ cook.first_name }}</p>
  <p>Last name : {{ cook.last_name }}</p>
  <p>Year of exp : {{ cook.year_of_experience }}</p>
  <p>Cooked dishes : {{ cook.dishes.count }}</p>
{% endblock %}

templates/kitchen/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Cook</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/cook_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Cook List
    <a href="{% url 'kitchen:cook-create' %}" class="btn btn-primary">
      Create
    </a>
  </h1>
  {% if cook_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Username</th>
        <th>Year experience</th>
      </tr>
      {% for cook in cook_list %}
        <tr>
          <td><a href="{% url 'kitchen:cook-detail' pk=cook.id %}">{{ cook.id }}</a></td>
          <td>{{ cook.first_name }}</td>
          <td>{{ cook.last_name }}</td>
          <td>{{ cook.username }}</td>
          <td>{{ cook.year_of_experience }}</td>
        </tr>
      {% endfor %}

    </table>
  {% endif %}
{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
	<h1>Delete {{ dish.name }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base.html"%}

{% block content %}
  <h1>{{ dish.name }}
    <a href="{% url 'kitchen:dish-update' pk=dish.id %}" class="btn btn-primary">Update</a>
    <a href="{% url 'kitchen:dish-delete' pk=dish.id %}" class="btn btn-danger">Delete</a>
  </h1>
  <p>ID : {{ dish.id }}</p>
  <p>Price : {{ dish.price }}</p>
  <p>Description : {{ dish.description }}</p>
  <p>Type : {{ dish.dish_type }}</p>
  {% for cook in dish.cooks.all %}
  	<p>Cook : {{ cook.username }}</p>
  {% endfor %}
  
{% endblock %}

templates/kitchen/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
 <h1>{{ object|yesno:"Update,Create" }} Dish</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dish_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Dish List
    <a href="{% url 'kitchen:dish-create' %}" class="btn btn-primary">
      Create
    </a>
  </h1>
  {% if dish_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Type</th>
      </tr>
      {% for dish in dish_list %}
        <tr>
          <td>
            <a href="{% url 'kitchen:dish-detail' pk=dish.id %}">{{ dish.id }}</a>
          </td>
          <td>
            {{ dish.name }}
          </td>
          <td>
            {{ dish.price }}
          </td>
          <td>
            {{ dish.dish_type }}
        </tr>
      {% endfor %}
    </table>

  {% endif %}
{% endblock %}

templates/kitchen/dish_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
	<h1>Delete dish type?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>
{% endblock %}

templates/kitchen/dish_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
 <h1>{{ object|yesno:"Update,Create" }} dish type</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dish_type_list.html
{% extends "base.html" %}

{% block content %}
  <h1>All Dish Types
    <a href="{% url 'kitchen:dish-types-create' %}" class="btn btn-primary">
      Create
    </a>
  </h1>
  {% if dish_type_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for dish_type in dish_type_list %}
        <tr>
          <th>{{ dish_type.id }}</th>

          <th>{{ dish_type.name }}</th>
          <th><a href="{% url 'kitchen:dish-types-update' pk=dish_type.id %}">Update</a></th>
          <th><a href="{% url 'kitchen:dish-types-delete' pk=dish_type.id %}">Delete</a></th>
        </tr>
      {% endfor %}
    </table>
    <ul>


    </ul>
  {% endif %}
{% endblock %}

templates/kitchen/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Kitchen service</h1>
    <p>Welcome to Kitchen service</p>
    <ul>
        <li><strong>Dish types:</strong> {{ num_dish_type }}</li>
        <li><strong>Dishes:</strong> {{ num_dish }}</li>
        <li><strong>Cooks:</strong> {{ num_cooks }}</li>
    </ul>

{% endblock %}